### ISSUE TITLE
Cancelled user has user.paid = true

### ISSUE THREAD

**Issue by bilalsattar24** [Glench/ExtPay#159] opened 2023-08-07 18:38 UTC
**Describe the bug**

**To Reproduce**
(Assuming you are already a "paid" user using the developer email address on file.
1. Open payment page
2. Set status to cancelled (or any other unpaid option)
3. Check user.paid
4. It's still set to true.

**Expected behavior**
I would expect user.paid to return false.

**Screenshots**
Please see that the user is "cancelled" on the payment page but user.paid is still set to true.
<img width="680" alt="Screenshot 2023-08-07 at 11 29 39 AM" src="https://github.com/Glench/ExtPay/assets/16925652/14377a0b-4c6c-4389-9398-da5a50b15eba">

**Desktop (please complete the following information):**
 - MacOS
 - Chrome
- Version: 115.0.5790.170

**Additional context**
Additionally, is there a way to "sign out" of the current user? Once signing in via the payment page, I don't see a way to log out or change the user.

**Comment by bilalsattar24** [comment] 2023-08-19 16:56
12 days and no response?

**Comment by Irishman25** [comment] 2023-08-20 18:45
Agreed. That's not a good look. I was about to integrate into a new extension but user above has a valid and critical callout that I don't see attention on. Is this still repo still active?

**Comment by Glench** [comment] 2023-08-21 14:13
Thanks for the report and the notification bump! I haven't reproduced it yet, but if this is indeed a real issue then it likely only happens in test mode. We'll take a look shortly.

**Comment by Irishman25** [comment] 2023-08-21 16:13
Awesome. Thanks for the quick follow up. This is a much needed source, I appreciate the hard work

**Comment by bsattar24** [comment] 2023-08-21 17:22
Thank you @Glench 

Please don't hesitate to reach out if there's any more information I can provide.

**Comment by Glench** [comment] 2023-08-22 14:50
I'm not able to reproduce this issue — it works exactly as expected when testing with a minimal example. Are you printing out user information directly from `extpay.getUser()`? Are you printing it out from a background page or from the chrome popup or from a content script?

**Comment by bilalsattar24** [comment] 2023-08-22 18:30
@Glench Thank you for taking a lot. I've spent some time trying to reproduce it again this morning, but it seems to be working as expected now. 

I can switch between the statuses and the user object reflects that. In the screenshot, I was printing that output directly from `extpay.getUser()`. I did call it from the function from a content script in the screenshot above.

**Comment by Glench** [comment] 2023-08-22 18:36
Hm ok, well if you can't reproduce it either then I'll close this for now. If you do end up finding an issue feel free to comment on it and I can reopen.

**Closed by Glench** 2023-08-22 18:36 UTC
